### ISSUE TITLE
Augury causing error with JIRA Software boards?

### ISSUE THREAD

**Issue by kcootedinh** [rangle/augury#721] opened 2016-10-04 23:15 UTC
The latest version of Augury, 1.2.1, seems to interfere somehow with boards in JIRA Software, v7.1.8. With the extension enabled an error notification occurs when viewing a board. I can disable the extension and the board works fine, and as soon as re-enabled the board shows the error again. 

I can't say what part of the board doesn't work either, everything seems to display fine.

I haven't noticed any issues with other sites / pages.

The error in the console is: 
An exception has occurred in http://jira.instance/secure/RapidBoard.jspa?rapidView=3 at 1:2 --- Uncaught SyntaxError: Unexpected token )

After looking at the network tab in the Dev Tools, when Augury is turned on this extra request is sent just before the error occurs, though I'm not sure if it's related.

```
XHR finished loading: GET "http://jira.instance/rest/whitelist/1/check?url=http%3A%2F%2Fjira.instance&_=1475621771995".
XMLHttpRequest.send @ batch.js?agile_global_admin_condition=true&is-server-instance=true&is-system-admin=true&jag=true&ja…:928
send @ batch.js?atlassian.aui.raphael.disabled=true&locale=en-AU:175
ajax @ batch.js?atlassian.aui.raphael.disabled=true&locale=en-AU:169
c.(anonymous function) @ batch.js?atlassian.aui.raphael.disabled=true&locale=en-AU:160
(anonymous function) @ batch.js?agile_global_admin_condition=true&is-server-instance=true&is-system-admin=true&jag=true&ja…:12183
postMessage (async)
ImmediateDefinition.canUsePostMessage @ ng-validate.js:32431
ImmediateDefinition @ ng-validate.js:32385
(anonymous function) @ ng-validate.js:32571
(anonymous function) @ ng-validate.js:32573
__webpack_require__ @ ng-validate.js:20
(anonymous function) @ ng-validate.js:31780
__webpack_require__ @ ng-validate.js:20
(anonymous function) @ ng-validate.js:18215
__webpack_require__ @ ng-validate.js:20
(anonymous function) @ ng-validate.js:23304
__webpack_require__ @ ng-validate.js:20
(anonymous function) @ ng-validate.js:29452
__webpack_require__ @ ng-validate.js:20
(anonymous function) @ ng-validate.js:21365
__webpack_require__ @ ng-validate.js:20
(anonymous function) @ ng-validate.js:18615
__webpack_require__ @ ng-validate.js:20
(anonymous function) @ ng-validate.js:32819
__webpack_require__ @ ng-validate.js:20
(anonymous function) @ ng-validate.js:13830
__webpack_require__ @ ng-validate.js:20
(anonymous function) @ ng-validate.js:18347
__webpack_require__ @ ng-validate.js:20
(anonymous function) @ ng-validate.js:32730
__webpack_require__ @ ng-validate.js:20
(anonymous function) @ ng-validate.js:33675
__webpack_require__ @ ng-validate.js:20
(anonymous function) @ ng-validate.js:47
__webpack_require__ @ ng-validate.js:20
(anonymous function) @ ng-validate.js:40
(anonymous function) @ ng-validate.js:43
batch.js:3 


```

**Comment by sumitarora** [comment] 2016-10-12 03:03
Seems related to this one: https://github.com/rangle/augury/issues/681

**Comment by third774** [comment] 2016-10-12 18:41
I'm also experiencing this issue.

**Comment by igor-ka** [comment] 2016-10-31 14:30
@kcootedinh and @third774  does this issue still happen? We think this might have been addressed in version 1.2.3 as part of a related bug fix. Let us know and we will help addressing it if needed.

**Comment by third774** [comment] 2016-10-31 15:51
@igor-ka it looks like I'm still having the issue. Will try to get some more helpful info for you.

**Comment by third774** [comment] 2016-10-31 16:15
From what I can tell, they add a "message" event listener to the window, and it is trying to eval a string that it expects to contain javascript, but is empty. I'm assuming the event must be triggering from Augury?

Let me know if there's any other debugging info you're curious about.

The first screenshot shows the empty string it is trying to eval

![image](https://cloud.githubusercontent.com/assets/8732191/19861417/7bf92902-9f5a-11e6-804e-2c0a929e9d9e.png)

The second screenshot is one step up in the call stack and shows the event listener.

![image](https://cloud.githubusercontent.com/assets/8732191/19861643/5a08dac6-9f5b-11e6-9e7d-3ef125c07e1a.png)

**Comment by igor-ka** [comment] 2016-10-31 19:46
thank you for the additional info @third774. We will try to look into this either this or next spring.

**Comment by third774** [comment] 2016-10-31 19:56
Spring or sprint? :P

**Comment by igor-ka** [comment] 2016-10-31 19:57
sprint ;)

**Comment by stevenkampen** [comment] 2016-11-03 16:22
@third774 I'm not having any luck reproducing this. With a new demo Jira board, everything appears to work fine, minus some errors in the console that persist even when Augury is disabled.

**Comment by readme42** [comment] 2016-11-04 10:33
@stevenkampen you asked here: https://github.com/rangle/augury/issues/766#issuecomment-258235860

> I'm just looking at this issue but having trouble reproducing it. Since I know you just ran into it also, can you give me any context I might be missing? I've attempted with a fresh Jira trial, using scrum and kanban boards. Anything you can think of?

The error occurs in the standard agile sprint board, here are some screenshots

![jira0](https://cloud.githubusercontent.com/assets/1941305/20002670/475f815c-a282-11e6-8b9b-7e1e2163f606.png)

![jira1](https://cloud.githubusercontent.com/assets/1941305/20002679/4abb42aa-a282-11e6-9613-d53162218184.png)

**Comment by stevenkampen** [comment] 2016-11-04 11:29
@readme42 I can reproduce now, but strangely enough, this is only a warning in my system (no notification over the app). Interesting, but it shouldn't stop me from debugging the issue. Cheers.

**Closed** 2016-11-17 20:19 UTC
Labels: bug, review needed
