### ISSUE TITLE
throw Converting circular structure to JSON error when use @ViewChildren

### ISSUE THREAD

**Issue by shjyh** [rangle/augury#446] opened 2016-06-20 10:13 UTC
the bootstrap component in my angular2 app has a property with **ViewChildren** annotation (type:QueryList) like this:
```
...
class Main{
    @ViewChildren(Day) days:QueryList<Day>;
    ...
}
```

augury throw the json error
>backend/ backend.ts

**_message.payload[0].state.days_** --> **circular structure**
```
let channel = {
  sendMessage: (message) => {
    return window.postMessage(JSON.parse(JSON.stringify({
      type: 'AUGURY_INSPECTED_APP',
      message
    })), '*');
  }
};
```

**angular version : 2.0.0-rc.2**
**augury version : 1.0.2 (chrome webstore)**

**Comment by sumitarora** [comment] 2016-06-21 02:55
@shjyh I tried with this example and it seems to be working fine. Can you elaborate on the example to reproduce the issue.

Running Example: http://run.plnkr.co/RGcuBiuYBJ0uwHvE/
Code: http://plnkr.co/edit/gbccLNGCthcENYiEch41?p=preview

**Comment by shjyh** [comment] 2016-06-21 03:04
**oh,sorry! the real reason is the input data of my Day component is a circular structure!**
is JSON.parse(JSON.stringify({...}) used to deepcopy message object?

**Comment by sumitarora** [comment] 2016-06-21 03:11
yes it is for that purpose only, basically serializable properties in the message object.

**Comment by kirjai** [comment] 2016-08-26 14:14
I am receiving the same `circular structure` error. And since it is being thrown by `zone.js` from within `backend.ts`. This causes further `zone.js` execution to be buggy. Which also breaks angular's internal change detection hence causing the angular application to be buggy. 

I've tore down my whole application trying to find a circular structure that might be causing this to happen, without any luck.. Hence I am fairly positive that it is not a circular structure that I have in my code, rather than something internal to, perhaps, Augury?

Removing Augury completely fixes any change detection bugs I have seen, also removes the `circular structure` error. My application is back to behaving predictably.

So the bottom line is that if I enable Augury in my browser, it causes my angular application to break. Due to the `circular structure` error, that I only see if Augury is enabled.

P.S. I believe this might be related to my comment on the following issue: https://github.com/rangle/augury/issues/422#issuecomment-242696599
The reason Augury might be failing after page refresh is because `zone.js` is buggy after throwing the `Circular Structure` error.

**Comment by clbond** [comment] 2016-08-26 15:30
I believe this has been fixed in the latest code. Would you mind checking out the rangle/augury dev branch and run:

```
npm install
npm run build
npm run pack
```

And install the resulting augury.crx file in your browser. If you see a white screen immediately after installing you should restart your browser since I think there may be an issue around installation / first load that I haven't had a chance to look at.

**Comment by clbond** [comment] 2016-09-06 21:58
This has long since been addressed by https://github.com/rangle/augury/commit/dfa410b6545f24e3cef87af775b4e9651ffad13f

**Closed** 2016-09-07 17:52 UTC
Labels: bug, investigation
