### ISSUE TITLE
Dependency graph corrupted?

### ISSUE THREAD

**Issue by slavede** [rangle/augury#1113] opened 2017-05-15 18:45 UTC
Augury version (required): 1.7.0
Angular version (required): 2.4.0
Date: 15th of May 2017
OS:
Win10
-- Please make sure you're using the latest version of Augury before reporting an issue.

Demo test application:
-- Git repository for demo app showing the issue (optional but very helpful for difficult issues).
-- If a code snippet will completely show the issue, please include it.

Description of issue:
-- Include (clipped) screenshot images if possible.
I have my app.module.ts
![image](https://cloud.githubusercontent.com/assets/2838038/26073399/0b8c777e-39af-11e7-8917-66ef838d0a70.png)

Inside of it it's app.component.ts:

![image](https://cloud.githubusercontent.com/assets/2838038/26073432/2a980c00-39af-11e7-955c-9d212430d7a2.png)

Further, this app.component.ts holds title.component.ts
![image](https://cloud.githubusercontent.com/assets/2838038/26073451/3efeb4b4-39af-11e7-9d70-dd5717da69c5.png)

Steps to reproduce:

1.
2.
3.

Additional details:

So notice that NewServiceService is injected and provided just at title.componet.ts, but in my dependency graphs it seems it's coming from root:

![image](https://cloud.githubusercontent.com/assets/2838038/26073512/64842584-39af-11e7-85e2-9904be755a30.png)

Based on the official docs, I would just expect line between title component and new service.

Is this expected behaviour what I'm getting (and why) or it is a bug?

**Comment by igor-ka** [comment] 2017-05-23 15:25
This is a duplicate of #1078, should be addressed shortly.

**Closed by igor-ka** 2017-05-23 15:25 UTC
