### ISSUE TITLE
TypeError: Cannot read property 'subscribe' of undefined

### ISSUE THREAD

**Issue by KeshavGeek** [rangle/augury#1413] opened 2019-11-09 11:35 UTC
![image](https://user-images.githubusercontent.com/6343303/68527952-18968100-0313-11ea-8842-480f86587a48.png)

Augury: 1.23.0
Date: Sat, 09 Nov 2019 11:34:51 GMT
OS: Linux x86_64

Demo test application:
-- Git repository for demo app showing the issue (optional but very helpful for difficult issues).
-- If a code snippet will completely show the issue, please include it.

Description of issue:
-- Include (clipped) screenshot images if possible.

Angular version (required): ???

Steps to reproduce:

1.
2.
3.

Additional details:

**Comment by yallen011** [comment] 2019-11-13 22:00
duplicate of #1383

**Comment by feeloor** [comment] 2019-11-14 09:33
Hi @KeshavGeek,
We see this issue on Angular < 4.
We leverage the ApplicationRef.isStable Observable, which was introduced in this commit (Angular v4 - Beta). The demo app is currently running version 2.4 which is why we see the issue on the demo app as well.

Please make sure to use Angular >= 4.

I'm going to close this issue in favour of #1383. Feel free to reopen if you feel this is a different issue.

Thanks.

**Closed by feeloor** 2019-11-14 09:33 UTC
Labels: duplicate
