### ISSUE TITLE
Router Tree view is empty, it doesn't show any route

### ISSUE THREAD

**Issue by MrCroft** [rangle/augury#715] opened 2016-09-30 17:46 UTC
I can't actually remember in what version of Augury/Angular 2, at some point, the Router Tree view in Augury actually showed me something (definitely before Angular reached RC.5, I'm just not sure how long before that or what version of Augury I was on)... I thought that it's a bug that can't be missed, so I didn't open any issue. But, since I still can't find any open issue for this, maybe I'm an isolated case or among a very few cases?

**Reproduction:**
Here's a demo app: https://github.com/MrCroft/lazy
I have 3 routes: Home, About and one that loads a lazy module.

```
    { path: '', component: HomeComponent },
    { path: 'about', component: AboutComponent },
    { path: 'lazy', loadChildren: 'app/lazy/lazy.module' }
```

I did find an issue reporting problems with `loadChildren`, but I still have 2 other routes (home and about).
My router tree in Augury is blank. Even if I take out the lazy module.

**Environment:**

```
Augury: 1.2.1 (but it behaved in the same way with 1.2.0 also, and I can't remember how long before that)
Angular: 2.0.0 / 2.0.1
Google Chrome: 53.0.2785.116 m (64-bit)
os: win32 x64
```

**Comment by igor-ka** [comment] 2016-09-30 18:14
@MrCroft thanks for reporting this. We are looking into addressing all the routing issues in the coming weeks. Also, thank you for providing an isolated repo with this use case.

I will keep this open for now, but it might be a duplicate of #628

**Comment by marinho** [comment] 2016-11-01 05:47
same to me: Augury 1.2.3, Angular 2.0.0

- one older and bigger application based on AngularClass/angular2-webpack-start
- other app is a brand new created with angular-cli

both fail the same way

**Comment by stevenkampen** [comment] 2016-11-02 10:33
@MrCroft @marinho Ok, it seems this is simply due to the Router not being injected into the root component (with the property name `router`). At the moment we rely on this being the case for the router tree to work.

From the (Augury README)[https://github.com/rangle/augury/blob/dev/README.md#supported-version]:
>To view the router graph inject the Router in the application root component as shown below (it must be named `router` exactly).
>```js
>export default class KitchenSink {
>  constructor(private router: Router) {
>  }
>}
```

**Closed** 2016-11-02 16:43 UTC
Labels: bug

**Comment by MrCroft** [comment] 2016-11-02 17:28
@stevenkampen injecting the Router in the root component, using the property name `router`, **does work** for me. Thank you!
I'm just wondering... Could this (at some point in the future) be fixed, so it won't matter where we inject the router?

**Comment by stevenkampen** [comment] 2016-11-02 17:29
@MrCroft I learned that there has been a conversation regarding that, with the core team, so I'm following it up. The plan has been that it would be improved in that way.
