### ISSUE TITLE
Unable to expand Component State Properties

### ISSUE THREAD

**Issue by tomwanzek** [rangle/augury#979] opened 2017-02-14 03:29 UTC
First of all, thanks for this wonderful development tool 👍 

I am currently experiencing the following issue. Component State Properties which are objects can no longer be expanded/collapsed in the Properties pane. E.g. `_element` in the below screenshot. The issue is independent of the component to be analyzed. This may possibly be related to a recent Chrome update, as I did  not experience the issue before.

I am running: Augury 1.2.11 now on Chrome Version 56.0.2924.87 (64-bit) (Windows 10 machine)

Thanks for looking  into it.

![augury-chrome issue](https://cloud.githubusercontent.com/assets/16323903/22913848/42a2231e-f23b-11e6-9c4c-4ae847144501.PNG)

**Comment by stevenkampen** [comment] 2017-02-14 11:07
@tomwanzek I think this will be a duplicate of #970 (issue with empty routers). The fix is in #980, and you can test that with an extension binary in the comments of #970. If you can confirm that this fixes it for you, then I'll close this. Thanks!

**Closed** 2017-02-14 16:57 UTC

**Comment by tomwanzek** [comment] 2017-02-15 21:22
@stevenkampen Thx for the swift response, I just checked and the latest release 1.2.12 indeed fixes the issue above 👍
