### ISSUE TITLE
Augury is very slow or not working

### ISSUE THREAD

**Issue by ArielGueta** [rangle/augury#970] opened 2017-02-13 16:51 UTC
I am using Chrome version 55. 

When I am trying to navigate to different sections like `NgModules` it's very slow or not working at all. 

The second thing is:

![alt text](https://s23.postimg.org/4t1xsxkij/Screen_Shot_2017_02_13_at_18_46_46.png "Screenshot")

When I am trying to click on the `filters` Input arrow nothing is happening.

**Comment by obambrough** [comment] 2017-02-13 21:28
Pressing the filter arrow (or any header, e.g. 'Injector Graph', 'Router Tree'...) does nothing, until you select a different element in the component tree, then navigate back to the previous component - the property will now be expanded (or the tab selected will be shown.) I reverted to Augury 1.2.10 and this fixed the problem.

**Comment by ArielGueta** [comment] 2017-02-13 21:30
How can I revert to 1.2.10?

**Comment by obambrough** [comment] 2017-02-13 21:33
Not sure if there's a proper way but I just went to the releases page (https://github.com/rangle/augury/releases) and downloaded the augury.crx for 1.2.10 and then dropped the downloaded file into my browser (I uninstalled the 1.2.11 first.) I'm not sure if extensions get automatically updated, but it is working for me right now.

**Comment by ArielGueta** [comment] 2017-02-13 21:34
OK, I will try this for now and will wait for the fix. Thanks.

**Comment by stevenkampen** [comment] 2017-02-14 10:22
@ArielGueta @obambrough Can either of you guys point to a repo that exhibits this issue? I'm not able to reproduce with our example apps so far.

**Comment by stevenkampen** [comment] 2017-02-14 10:54
@ArielGueta @obambrough I believe I've found the problem and have the fix in #980. It will be merged and released soon.

**Comment by stevenkampen** [comment] 2017-02-14 11:04
@ArielGueta @obambrough You can confirm this fix with this extension binary (rename from `zip` to `crx`).
[augury-1806.zip](https://github.com/rangle/augury/files/773866/augury-1806.zip)

**Comment by ArielGueta** [comment] 2017-02-14 11:39
I'm getting the error:
CRX_MAGIC_NUMBER_INVALID

**Comment by ArielGueta** [comment] 2017-02-14 11:40
I just changed the extension to crx and tried to load it manually in chrome://extensions/

**Comment by stevenkampen** [comment] 2017-02-14 14:04
I'm sorry. Try this one which is just the `crx` built locally and renamed to `zip`.
[augury.zip](https://github.com/rangle/augury/files/774260/augury.zip)

**Comment by ArielGueta** [comment] 2017-02-14 15:08
Working!

**Closed** 2017-02-14 16:57 UTC
Labels: bug, review needed

**Comment by stevenkampen** [comment] 2017-02-14 17:19
@ArielGueta @obambrough Fixed in 1.2.12. Update should come through automatically in the next couple of hours.

**Comment by obambrough** [comment] 2017-02-15 18:37
@stevenkampen Thanks!, that worked for me too.

**Comment by giovannischirano** [comment] 2017-09-25 18:39
Hi @stevenkampen, I have a similar problem on my Augury extension. It isn't working at all. When I open the tab I can only close it otherwhise it's all frozen (also mouse pointer doesn't point to the onover element).
