### ISSUE TITLE
IO Demo throwing uncaught exception in Augury tab

### ISSUE THREAD

**Issue by spsalsm** [rangle/augury#1391] opened 2019-05-21 14:34 UTC
-- please install the [Augury Canary Build](https://chrome.google.com/webstore/detail/augury-canary-build/leechohfifidanmkioncamdcibhmmcji?hl=en) Chrome extension, as this will be used to test any new features or bug fixes.

Augury version (required): 1.23.0
Angular version (required): 6.1.10
Date: 5/21/19
OS: Mac OS Mojave

-- Please make sure you're using the latest version of Augury before reporting an issue.

Demo test application:
-- Git repository for demo app showing the issue (optional but very helpful for difficult issues).
-- If a code snippet will completely show the issue, please include it.

Description of issue:

Trying to follow the Augury guide online, which uses the Augury Input Output Demo. When I go to the demo and open DevTools > Augury, I get the following:

![image](https://user-images.githubusercontent.com/518407/58105074-83a89b80-7bab-11e9-8878-795600fb4f82.png)

Steps to reproduce:

1. Go to https://augury.rangle.io/examples/input-output/app/index.html
2. Open DevTools
3. Select Augury tab

Additional details:

**Comment by GurpreetSingh5** [comment] 2019-06-19 12:12
Facing this too. In both Chrome and Firefox.

**Comment by GurpreetSingh5** [comment] 2019-06-28 06:13
Any update on this?

**Comment by yallen011** [comment] 2019-10-29 20:46
duplicate of #1383

**Comment by feeloor** [comment] 2019-11-15 14:02
We've now updated the example application to Angular 8, which solved the issue. 
Please give it a new try, and feel free to reopen this issue if there still are issues.

**Closed by feeloor** 2019-11-15 14:02 UTC
Labels: duplicate
