### ISSUE TITLE
Reload of browser window breaks augury

### ISSUE THREAD

**Issue by steveblue** [rangle/augury#377] opened 2016-05-04 20:40 UTC
When reloading the browser window, the augury view in dev tools seems to fail. When closing the window and opening again, the view loads properly. Refreshing the augury view after the browser reloads is a MUST have feature, currently I cant use this tool with a livereload server. 

Reproducible in Chrome  52.0.2724.0 canary (64-bit) and Version 50.0.2661.94 (64-bit) OS X.

See before and after reload below:

<img width="1436" alt="screen shot 2016-05-04 at 2 37 23 pm" src="https://cloud.githubusercontent.com/assets/1171943/15028380/dea381c0-1205-11e6-9a12-da00678bbd7d.png">
<img width="1440" alt="screen shot 2016-05-04 at 2 37 37 pm" src="https://cloud.githubusercontent.com/assets/1171943/15028381/deb2d580-1205-11e6-9d85-ecd69ed34cc2.png">

**Comment by sumitarora** [comment] 2016-05-04 20:41
@steveblue We will be pushing the latest soon that will fix the issue thanks

**Comment by steveblue** [comment] 2016-05-04 20:41
Awesome! Can't wait!

**Comment by sumitarora** [comment] 2016-05-16 15:14
Duplicate of https://github.com/rangle/augury/issues/386 closing this one

**Closed by sumitarora** 2016-05-16 15:14 UTC
Labels: bug
