### ISSUE TITLE
External augury report

### ISSUE THREAD

**Issue by lokeshneelam** [rangle/augury#1116] opened 2017-05-17 03:05 UTC
Its not an issue, more a question - 

Is there any way I can extract augury report in external file?

**Comment by stevenkampen** [comment] 2017-05-23 15:23
@lokeshneelam You mean something representing what Augury shows in the UI at any point? The issue is that this info is highly dynamic, so it doesn't seem so useful to create a printable snapshot of that info. Let me know what you think, and maybe more about your use case.

**Comment by lokeshneelam** [comment] 2017-05-30 05:33
Yes that's what I meant. I looking some automation script (already in place or modify the existing) which can generate augury report externally without using the chrome extension. Is it possible?

**Comment by igor-ka** [comment] 2017-05-30 16:45
Hey @lokeshneelam i am still not sure what kind of data you would like to get out of Augury for your report? Do you want data associated with the component tree, inspector graph, or maybe NgModules tab? I'd like to get a better understand of this.

**Comment by lokeshneelam** [comment] 2017-05-31 03:52
'Component Tree' and 'ngModule' tab.

**Comment by igor-ka** [comment] 2017-06-09 18:20
Hey @lokeshneelam we discussed this between the team and a this time this feature is relatively low value in our opinion. This is mainly due to the fact, that the component and even router trees are dynamic in nature and can change at runtime frequently whereas the report is more appropriate for static things that do not change often like ngModule tab.

This is a low priority for us, but at the same time we will be happy to review a PR implementing this for NgModules if you want.

Otherwise, I will be closing this issue for now.

**Closed by igor-ka** 2017-06-09 18:20 UTC
Labels: question
