### ISSUE TITLE
Indication of Angular presence

### ISSUE THREAD

**Issue by mfulton26** [rangle/augury#1343] opened 2018-09-13 13:18 UTC
[React Developer Tools](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi) and [Vue.js devtools](https://chrome.google.com/webstore/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd) each appear in Chrome with a different color icon depending on the presence of React/Vue in the current page. e.g.:

- Full color for production build being used on the page
- Full color with some warning indication when it is a prod build but not the latest version
- Colored with red or something to indicate a dev build is being used on the page
- Grayed out when the library isn't being used at all

It would be great if, at a minimum, Augury was greyed out if it isn't applicable on the current page but it would be even better in my opinion if it had different shade/color icons (or indicators on the icon) depending on prod latest, prod old, dev, etc.

Thanks!

**Comment by andrewthauer** [comment] 2018-10-30 13:51
Thanks for the suggestion. This is a duplicate of #1280.

**Closed by andrewthauer** 2018-10-30 13:51 UTC
