### ISSUE TITLE
'Loading...' after Canary update?

### ISSUE THREAD

**Issue by tycho01** [rangle/augury#394] opened 2016-05-14 09:15 UTC
I just updated my Chrome Canary version to `52.0.2735.0` (64-bit), and it appears Augury is stuck on 'Loading...' for me now. I can't exclude other causes yet, but was wondering if anyone else had experienced something similar. If not, I'm clueless atm and this can be closed.

**Comment by igor-ka** [comment] 2016-05-16 14:52
Response on github issue is required

**Comment by tycho01** [comment] 2016-05-16 14:57
@igor-ka: Sorry, I'm a bit confused as to what you meant by response. Could you elaborate please?
I'm still experiencing this issue; neither browser restarts nor Augury reinstalls appear to be fixing it for me so far.

**Comment by igor-ka** [comment] 2016-05-16 17:22
@tycho01 sorry for the confusing response :)

We will investigate this issue, as we need to figure out if this is a Chrome Canary issue (which seems to work for us) or if this is something else.

It would be great if you could tell us which version of angular2 you are using as well. We will be releasing a version that supports RC1 very soon. Otherwise, I we only support the beta for now.

PS. Also your app needs to run in dev mode for Augury to work

**Comment by st-clair-clarke** [comment] 2016-05-16 19:25
I am experiencing the same problem with Canary (latest version) too. No such problem with Chrome.

**Comment by sumitarora** [comment] 2016-05-16 19:46
@tycho01 @st-clair-clarke In the latest update of the chrome `window.postMessage` has been deprecated this is the reason why it's not working see the message below. We will investigate if it's possible to support both the versions with the next Augury Release

> 'window.postMessage(message, transferables, targetOrigin)' is deprecated and will be removed in M54, around October 2016. Please use 'window.postMessage(message, targetOrigin, transferables)' instead. See https://www.chromestatus.com/features/5719033043222528 for more details.

**Comment by tycho01** [comment] 2016-05-17 02:44
Thank you for the update. Interestingly, I had been using Augury with ng2 RC1 in production mode. Only after the Canary update did I start experiencing issues. But this sounds hopeful; until resolved I'll try stable Chrome then. :)

**Comment by clbond** [comment] 2016-06-13 22:47
It turns out this had nothing to do with the postMessage API being changed. It was a result of our recursive node-item component not working in Chrome Canary. First I determined that the promise being returned by bootstrap() was never resolved or rejected. Then I did some extensive debugging of runtime_compiler.js and was able to determine that ultimately the promise that was hanging the application was associated with node-info. From there, I took out the recursive reference in [directives] and in the .html file and it completely resolved the issue, and the application was able to start correctly. Then with some trial and error, I noticed that changing the component from using templateUrl to template actually resolves the problem. So there is something about the interplay of templateUrl and recursive components which does not work on Chrome Canary. It's not clear whether this is a Chrome bug or an Angular 2 bug, but nonetheless the issue is fixed by this PR: https://github.com/rangle/augury/pull/425

**Closed** 2016-06-23 20:21 UTC
Labels: investigation, review needed
