### ISSUE TITLE
This application is running in production mode and therefore cannot be inspected using Augury.  If this is an Angular application, please rebuild your application in debug mode or remove the call to enableProdMode().

### ISSUE THREAD

**Issue by AgSpaceSupport** [rangle/augury#1390] opened 2019-05-20 09:58 UTC
Augury: 1.23.0
Date: Mon, 20 May 2019 09:58:30 GMT
OS: Win32

Demo test application:
-- Git repository for demo app showing the issue (optional but very helpful for difficult issues).
-- If a code snippet will completely show the issue, please include it.

Description of issue:
-- Include (clipped) screenshot images if possible.

Angular version (required): ???

Steps to reproduce:

1.
2.
3.

Additional details:

**Comment by JimMorrison723** [comment] 2019-05-23 12:37
I don't think anyone can help you without adding more details to the issue.
Steps to reproduce?
Are you sure you are not running the app in production mode?

**Comment by davidduckwitz** [comment] 2019-07-02 16:11
Same Problem...
- Angular 8
- Augury: 1.23.0
- MacOS Mojave

I'm sure not running in ProdMode...
Tested in Firefox & Google Chrome

**Comment by yallen011** [comment] 2019-10-29 20:45
duplicate of #1383

**Comment by yallen011** [comment] 2019-11-15 22:07
closing is favor of #1383 which has been resolved and closed.

**Closed** 2019-11-15 22:07 UTC
Labels: duplicate
