### ISSUE TITLE
State panel does not allow scrolling in Firefox

### ISSUE THREAD

**Issue by fluffynuts** [rangle/augury#1346] opened 2018-09-20 11:41 UTC
Augury version (required): 1.19.3
Angular version (required): 6.1.7
Date: 2018-09-20
OS: Windows 10

Description of issue:
When inspecting a component with lots of properties or properties into which you can drill quite deeply (eg observable property), tree expansion causes the "Dependencies" pane and state information nodes near the bottom of the view to disappear. 

Before expansion:
![image](https://user-images.githubusercontent.com/4669340/45815940-71075b00-bcda-11e8-9285-76b73ce4b6ca.png)

After expansion:
![image](https://user-images.githubusercontent.com/4669340/45815964-81b7d100-bcda-11e8-9574-a4723419c215.png)

This is evident in Firefox stable and nightly, however both the canary and regular versions of the Chrome plugin do not exhibit this behavior.

Steps to reproduce:

1. Install Augury on Firefox
2. Load up angular application
3. Select Augury developer tab
4. Select a component with many properties or one where a property is an observable (has a long drill-down available)
5. Expand tree nodes in the State view until the Dependencies view header disappears and nodes start disappearing out of vew
6. Attempt to scroll down and fail -- there are no scroll bars and mouse scrolling does not work; neither do any keypresses (eg up/down)

**Comment by santiago-elustondo** [comment] 2018-09-20 19:42
Hey @fluffynuts, thanks a lot for this detailed bug report.
We will look into it and get back to you with a fix.

**Comment by weaversam8** [comment] 2018-12-13 22:09
Any progress on this? I can confirm this issue still exists and it affects me. 

Augury version (required): 1.21.0
Angular version (required): 4.2.4 (`@angular/core` version in package.json, not sure if that's right)
Date: 2018-12-13
OS: Windows 10
Firefox Version (should probably include this): Firefox Developer Edition 65.0b2

**Comment by sergray** [comment] 2018-12-14 13:40
The problem is also experienced in

Augury version: 1.21.0
Angular version: 6.0.7
Date: 2018-12-14
OS: Ubuntu 17.10
Firefox: 61.0.1

**Comment by roukaour** [comment] 2019-01-10 21:49
I am also experiencing this issue with up-to-date Firefox and Augury newly installed..

Augury version: 1.21.0
Angular version: 7.0.3
Date: 2019-01-10
OS: Windows Server 2016
Firefox: 64.0.2

**Comment by cdarken** [comment] 2019-01-15 09:06
Same behavior now on Chrome Beta: 72.0.3626.53 (Official Build) beta (64-bit)
Augury version: 1.22.0
Angular: 7.1
OS: Ubuntu Linux

Hoping is just temporary and this will not be broken in the next stable version.

**Comment by nxtreme** [comment] 2019-03-13 08:16
Hello,
same bug on my side
Augury 1.22.0
angular 7.1.2
google chrome 72
Windows 10

the workaround I'm using since the bug came up : select text and CTRL+SHIFT+key up/down

**Comment by cdarken** [comment] 2019-03-13 16:33
For anyone else having issues with this, the dev branch works fine.

**Comment by jcletousey** [comment] 2019-03-14 09:14
Windows 10
Firefox 65.0
Chrome 72.0
Angular 7.0.4

For Firefox, on addons.mozilla.org, Augury version is 1.21.0 while for Chrome, on its store, it is 1.22.0. Both versions are not working for this particular issue.

I cloned the project, checkout the ```dev``` branch because I saw [this commit](https://github.com/rangle/augury/commit/368d3c29a75fea1e33c7298a0e54546d5dccdfc3) that resolves the problem. I followed the _Building and installing locally_ procedure in the ```README.md``` file and actually it works. On Firefox, the problem with this solution is that you have to re-install the local extension on every launch. I don't know if it is the same for Chrome.

I hope that the next release will be soon ;-)

**Comment by nick-beers** [comment] 2019-03-26 17:11
Do the devs have any update on when this may potentially be fixed? As was mentioned by jcletousey it seems that the issue may be fixed in the next release (at least for Firefox), but looking at prior releases there isn't really a pattern to when releases typically occur.

**Comment by JessicaBarnett** [comment] 2019-03-28 17:03
I'm experiencing this in chrome as well, and am eagerly awaiting the next release :)
Augury: 1.22.0
Chrome: 73.0.3683.86 
Angular: 5.2.11
Mac OS Sierra 10.12.6

**Comment by andrewthauer** [comment] 2019-04-02 18:34
Fixed in [Release 1.23.0](https://github.com/rangle/augury/releases/tag/1.23.0)

**Closed by andrewthauer** 2019-04-02 18:34 UTC
Labels: bug
