### ISSUE TITLE
DoDear TV

### ISSUE THREAD

**Issue by HeartDisk** [rangle/augury#1357] opened 2018-12-14 18:50 UTC
Augury: 1.21.0
Date: Fri, 14 Dec 2018 18:52:20 GMT
OS: Win32

Demo test application:
-- Git repository for demo app showing the issue (optional but very helpful for difficult issues).
-- If a code snippet will completely show the issue, please include it.

Description of issue:
-- Include (clipped) screenshot images if possible.

Angular version (required): ???

Steps to reproduce:

1.
2.
3.

Additional details:

**Comment by stevenkampen** [comment] 2018-12-21 10:15
@HeartDisk I'm going to close this because it doesn't contain any info about reproduction at all. The only info I have to go on is "DoDear TV".

I'm happy to look into any issue, but you do have to follow the protocol for describing the problem and the steps for reproduction.

**Closed by stevenkampen** 2018-12-21 10:15 UTC
