### ISSUE TITLE
Augury slow and not working

### ISSUE THREAD

**Issue by giovannischirano** [rangle/augury#1246] opened 2017-09-27 16:57 UTC
Augury version (required): 1.14.0
Angular version (required): 4.4.3
Date: 27/09/2017
OS: Windows 10

-- Please make sure you're using the latest version of Augury before reporting an issue.

Demo test application:
-- Git repository for demo app showing the issue (optional but very helpful for difficult issues).
-- If a code snippet will completely show the issue, please include it.

Description of issue:
-- Include (clipped) screenshot images if possible.
Augury isn't working at all. When I open the tab I can only close it otherwhise it's all frozen (also mouse pointer doesn't point to the onover element).

Steps to reproduce:

1. Open Developer Tools
2. Go on Augury Tab
3. It isnt't working at all

Additional details:
If I add some elements in the page I see some on the tab but it is not usable.

**Comment by jasonjustice73** [comment] 2017-09-28 12:05
I am experiencing this as well and I have the same OS (Windows 10), Angular Version (4.4.3) and Augury (1.1.4) as giovanni.

**Comment by giovannischirano** [comment] 2017-10-08 18:20
The problem seems to be solved. @jasonjustice73 do you still face the issue?

**Comment by bujardeari** [comment] 2017-10-13 13:03
I am still experiencig the same !

**Comment by bujardeari** [comment] 2017-10-13 13:16
#1242

**Comment by andrewthauer** [comment] 2018-05-11 15:33
@bujardeari - Would you mind verifying if this is an issue with the latest release?

**Comment by santiago-elustondo** [comment] 2018-05-24 17:32
This issue should be fixed with version 1.18.
Please reopen if you are still experiencing this.

**Closed by santiago-elustondo** 2018-05-24 17:32 UTC
Labels: pending fix verification

**Comment by bujardeari** [comment] 2018-06-29 12:07
@andrewthauer I am to late  the issue is closed, but i can also confirm that the issue is gone.

**Comment by santiago-elustondo** [comment] 2018-06-29 12:43
thanks, @bujardeari
