### ISSUE TITLE
missing "state" in component properties tab

### ISSUE THREAD

**Issue by luckylooke** [rangle/augury#992] opened 2017-02-22 08:07 UTC
Augury version (required): latest - 1.2.12
Angular version (required): 2.2.1
Date: 22. Feb 2017
OS: Mac OSX Sierra 10.12.3 (16D32)
Chrome: 56.0.2924.87 (64-bit)

Demo test application:
`ionic start myApp sidemenu --v2`

Description of issue:
non of the component has state property
http://prntscr.com/ebw6qc

Steps to reproduce:

1. click any component
2. state not shown

Thank you

**Comment by luckylooke** [comment] 2017-02-22 09:01
I have tested it in another app (augury demo) and I was able to find state in Form2 component, so problem seems to be in app design/dependencies/...
http://prntscr.com/ebwpps

I will look at implementation and let you know soon..

**Comment by luckylooke** [comment] 2017-02-22 09:14
I was trying to apply:
```ts
import { BrowserModule } from '@angular/platform-browser';
import {platformBrowserDynamic} from "@angular/platform-browser-dynamic";
```
from example:
https://github.com/rangle/augury/blob/55fe09a361a7321fc3c235e50fa57205d2f933b7/example-apps/kitchen-sink-example/source/app.ts

to my app module, but still `state` property not shoving up :/

Here is my app.module:
```ts
import { NgModule, ErrorHandler } from '@angular/core';
import { HttpModule, JsonpModule } from '@angular/http';
import { FormsModule }   from '@angular/forms';
import { IonicApp, IonicModule, IonicErrorHandler } from 'ionic-angular';

import { BrowserModule } from '@angular/platform-browser';
import {platformBrowserDynamic} from "@angular/platform-browser-dynamic";

import { UserService } from '../services/user.service';
import { HttpX } from '../services/httpx.service';

import { MyApp } from './app.component';

import { Login }		from '../pages/account/login/login';
...
import { Company }		from '../pages/profiles/company/company';

import { EqualValidator } from "../directives/equal-validator.directive";

let entryComponents = [
	MyApp,
...
];

let declarations = [
	MyApp,

	// intro
    Splash,
	Login,
	 ...
];

let links = [
	{ component: Login,			segment: 'login' },
	...
];

@NgModule({
	declarations: declarations,
	entryComponents: entryComponents,
	imports: [
		IonicModule.forRoot(MyApp, {
			mode: 'ios',
		}, {
			links: links,
		}),
		BrowserModule,
		FormsModule,
		HttpModule,
		JsonpModule,
	],
	bootstrap: [IonicApp],
	providers: [{provide: ErrorHandler, useClass: IonicErrorHandler}, UserService, HttpX]
})
export class AppModule {}

platformBrowserDynamic().bootstrapModule(AppModule);
```

**Comment by stevenkampen** [comment] 2017-02-27 11:23
@luckylooke Can you provide a repo that this can be reproduced on, or exact instructions to create and run an app where this is possible?

**Comment by stevenkampen** [comment] 2017-02-27 11:26
This is possibly a duplicate of https://github.com/rangle/augury/issues/992

**Comment by trognus** [comment] 2017-02-28 18:16
I'm seeing this when I include ChangeDetectorRef as a dependency (removing works fine).

**Comment by luckylooke** [comment] 2017-02-28 18:43
@stevenkampen this is #992.. anyway, I will try to reproduce it somewhere public.. perhaps this week.

**Comment by stevenkampen** [comment] 2017-03-02 16:22
@luckylooke haha thanks :)

**Comment by luckylooke** [comment] 2017-03-19 12:22
@stevenkampen, hi! :) 
So I have managed to make some time for this and I have created repo for reproducing this issue here: https://github.com/luckylooke/auguryissue

after cloning repo, install dependencies vie npm i and run dev server ionic serve it will automatically open browser I have putted some test properties to HomePage component You can find HomePage component in augury on this path: IonicApp/MyApp/Nav/TabsPage/Tabs/Tab/HomePage

as you see there is no state :/

I am expecting my properties: myTestProperty myTestProperty2 from /src/pages/home/home.ts

to be shown

Thanks ;)

**Closed** 2017-03-29 16:28 UTC
Labels: bug, review needed
