### ISSUE TITLE
Failed to load component state

### ISSUE THREAD

**Issue by aliShreef** [rangle/augury#1373] opened 2019-03-04 20:36 UTC
Augury: 1.22.0
Date: Mon, 04 Mar 2019 20:33:28 GMT
OS: Win64

Demo test application:
  <form #userForm="ngForm" (ngSubmit)="save(userForm)">
    <div class="form-group">
      <label>User Name</label>
      <input class="form-control" type="text" name="name" ngModel>
    </div>
  
    <div class="form-group">
      <label>User Email</label>
      <input class="form-control" type="text" required ngModel #email="ngModel"  name="email" >
      <small>{{email.valid}}</small>
    </div>
  
    <div class="form-group">
      <label>User Phone</label>
      <input class="form-control" type="text" #phone name="phone" [(ngModel)]="phone1">
    </div>
  
    <div class="form-group">
      <label>User Gender</label>
      <input class="form-control" type="text"  name="gender" ngModel>
    </div>

    <div ngModelGroup="adress">
  
      <div class="form-group">
        <label>User City</label>
        <input class="form-control" type="text"  name="city" ngModel>
      </div>
    </div>

    <button class="btn btn-primary" type="submit">Save</button>
  </form>

Description of issue:
when i start application and open debug tool i got this message in state of property tab 

Angular version (required): 7.1.4

Steps to reproduce:

1.create simple app 
2. build simple form as above
3-launch debug tool

**Comment by aliShreef** [comment] 2019-03-12 19:37
Any Idea!

please help

**Comment by AryanJ-NYC** [comment] 2019-03-14 15:11
@aliShreef Go to `polyfills.ts` and comment out `import 'core-js/es6/date';`.

Dupe of https://github.com/rangle/augury/issues/1368

**Comment by john3794** [comment] 2019-03-19 18:25
It still does not work? Anyone knows the current situation?

**Comment by AryanJ-NYC** [comment] 2019-03-19 19:00
Again, please refer to https://github.com/rangle/augury/issues/1368.

**Comment by aliShreef** [comment] 2019-03-27 08:37
Hi Johnny

sorry for late reply but i was busy the last few days.

regarding this point i tried as you told me but still give me the same
message .

i will attache screenshot for that

thank you for interesting and waiting for this bug to fix;

and thank you for your effort in this project , actually it will help me a
lot in development .

best regards,,,,

**Comment by andrewthauer** [comment] 2019-04-01 16:29
Seems like a duplicate and/or related to #1368.

**Closed by andrewthauer** 2019-04-01 16:29 UTC
