### ISSUE TITLE
Scroll for Router tree tab

### ISSUE THREAD

**Issue by protekshen** [rangle/augury#1363] opened 2019-01-24 12:24 UTC
Augury version (1.22.0):
Angular version (5.2.11):
Date: 24.01.2019
OS: MacOs 10.14 (18A391)
Browser: Chrome, latest version (Version 73.0.3679.0 (Official Build) dev (64-bit)

Description of issue: the tab `Router tree` does not have scroll function  when we have really big `Router tree`, it's problem. I can't to see all router tree in browser.

<img width="761" alt="screenshot 2019-01-24 at 15 13 39" src="https://user-images.githubusercontent.com/13870417/51677900-1c5b5000-1fec-11e9-92e8-385ff9cad069.png">

Steps to reproduce:

1.  need the big router tree for get this problem

Added information:

Interesting thing, it is works for my friend, he has next settings:
Augury version (1.22.0):
Angular version (5.2.11):
Date: 24.01.2019
OS: MacOs 10.14.1
Browser: Chrome, (Version 71.0.3578.98 (Official Build) (64-bit))

Please compare this with my setting when we will check it.

**Comment by andrewthauer** [comment] 2019-04-01 16:37
Duplicate of #1361

**Closed by andrewthauer** 2019-04-01 16:37 UTC
