### ISSUE TITLE
Angular 5 breaks augury

### ISSUE THREAD

**Issue by zoharyosef** [rangle/augury#1253] opened 2017-11-21 12:32 UTC
Augury version 1.14.0:
Angular version 5.0.1:
Date: 21.11.17
OS: Win10

Description of issue:

Component state doesnt show anything!
(the little white box on the right side below "dependencies")
it use to show me all ther properties on angular 4.2.2, and was very helpfull,
ever since we upgraded to angular 5 though, we can't see anything there.

Steps to reproduce:

1. Make an angular 5 app.
2. Run augury.

Thanks a lot you are awesome!

**Comment by quanological** [comment] 2017-11-25 02:47
Experiencing the same issue. Same steps as the person above to reproduce the issue. If you need any help please let me know through my email. 

Details:
Augury v. 1.14.0
Angular v. 5.0.1
Version 62.0.3202.94 (Official Build) (64-bit)
Mac OS 10.12.6

**Comment by idanb11** [comment] 2017-12-08 16:10
:+1:

**Comment by santiago-elustondo** [comment] 2017-12-22 19:02
Can you provide an example where this occurs? We are currently seeing normal behaviour inspecting an Angular 5 app.
![screen shot 2017-12-22 at 2 00 28 pm](https://user-images.githubusercontent.com/10526720/34309576-bfff28fe-e720-11e7-82d2-fbacd4ce5ecf.png)

**Comment by distante** [comment] 2018-01-07 10:30
I have the exact same issue in an Ionic 3 Project using Angular 5.0.3  There is no State tab

**Comment by clabough** [comment] 2018-02-08 22:59
I think it might be related to what it thinks is a component and what it thinks is not.  In my 5.2.4 app, some of the components are not showing state, but a few are.  If I switch Augury modes to "All components and elements" or "Components only", most of the components and elements disappear from the Component Tree. "Hybrid view" shows the most items in the Component Tree, but some of them show state and some do not.

**Comment by rossjcooper** [comment] 2018-02-21 08:53
I am also getting this issue on Angular 5.1.2, although it was working a week or so ago.
I do not see any state box at all for any of my components.
![screen shot 2018-02-21 at 08 52 54](https://user-images.githubusercontent.com/3597958/36470959-a55b309e-16e4-11e8-92b5-08047e3e8965.png)

**Comment by rossjcooper** [comment] 2018-02-21 08:58
Annoyingly I cannot reproduce this issue either, I wonder if it is when an app gets to a certain size or X amount of nested components?
[Angular 5 Demo App](https://angular-c9qvdq.stackblitz.io/)

**Comment by dragGH102** [comment] 2018-03-14 12:59
I can confirm the issue. state shows up only for certain components, notably not including deeply nested ones

**Comment by santiago-elustondo** [comment] 2018-04-02 19:45
Hi everyone. I would like to get this resolved.
If you could point me to an app that shows this bug, I can get it cleared up.

@rossjcooper 's demo looks normal to me, although it is a very small example app with 1 component.
<img width="924" alt="screen shot 2018-04-02 at 3 32 26 pm" src="https://user-images.githubusercontent.com/10526720/38212259-142d8844-368b-11e8-93a2-f97e6a2516e5.png">

**Comment by clabough** [comment] 2018-04-03 17:09
@santiago-elustondo  I wish I could provide you a copy of my project, but it is an internal copyrighted project. Is there some additional diagnostics/testing that I could do to assist you with tracking this down? Or could you add a diagnostics reporting tool to the extension?

**Comment by santiago-elustondo** [comment] 2018-04-06 13:51
@clabough, we're currently in the process of building out just that.
It has become a big refactoring job as well, but we expect a release before the end of the month.
You can follow the progress [here](https://github.com/rangle/augury/pull/1272) and [here](https://github.com/rangle/augury/pull/1282).

**Comment by timmackey** [comment] 2018-04-10 18:12
I am experiencing the same issue.  My Angular 5 project is based on ASP.NET Boilerplate.  You can download publicly available source code from here: [https://aspnetboilerplate.com/samples](url)

**Comment by rossjcooper** [comment] 2018-04-17 08:03
I've moved from Chrome as I'm finding it more and more buggy for developer tools and have switched to Opera, yes I know its based on Chromium but it seems to work a lot better.

I have managed to install Augury into Opera and the state debug works on the same app that I originally had this issue with when using Chrome.

**Comment by rossjcooper** [comment] 2018-04-24 11:00
@jainvishal520 Opera and Chrome are almost the same browser as they are both built on Chomium, if you can download the extension file then you just drag it into the extensions page on Opera and it will work most the time.

**Comment by jainvishal520** [comment] 2018-04-25 08:27
@rossjcooper Thanks a lot, it works perfectly in opera. It is a good workaround till this issue is fixed.

**Comment by distante** [comment] 2018-04-29 11:14
Does anybody know how can I download the extension so I can install it on Opera?

**Comment by itsnotvalid** [comment] 2018-05-11 02:54
Just a friendly reminder, angular 6 is released so it's likely to break something here or there again.

**Comment by andrewthauer** [comment] 2018-05-11 17:26
Augury 1.16.0 fixed a few other Angular 5 related issues. We also tested against Angular 6 which did not introduce any known issues. Closing this under the assumption the latest version fixes the issue. Feel free to open a new issue with additional details.

**Closed by andrewthauer** 2018-05-11 17:26 UTC
Labels: bug, can't reproduce
