### ISSUE TITLE
Empty Augury Tab - Vivaldi Support?

### ISSUE THREAD

**Issue by negue** [rangle/augury#987] opened 2017-02-19 19:43 UTC
It seems that the `tabId` is null, (atleast thats what the errors write).  I tried to fix it myself but it won't work ^^, `chrome.devtools.inspectedWindow` stays undefined, maybe this has to be called by a different context? 

Although it seems to work for https://github.com/zalmoxisus/redux-devtools-extension/issues/116

Augury version (required): latest + git 
Angular version (required): 2.4.6
Date: 19. February
OS: Mac+Windows

**Comment by stevenkampen** [comment] 2017-02-27 11:24
@negue Can you elaborate on the issue you're seeing, and how you're producing it?

**Comment by negue** [comment] 2017-02-27 21:59
Vivaldi - Extensions - Developer Mode
- load unpacked extensions (point to local repo of augury, which was built with `npm run dev-build`)
- click on „background  page“ (which opens the console for augury itself, but i guess you know that already xD
- open any angular2 app
- open augury tab in inspector of that angular2
- get an error in the „background page“ console

`Error in event handler for (unknown): Error: Invocation of form tabs.sendMessage(null, object) doesn't match definition tabs.sendMessage(integer tabId, any message, optional object options, optional function responseCallback)
    at listener (chrome-extension://ljgiffejdendkhlolgiahkpanieclaan/build/channel.js:5551:22)`


    `chrome.tabs.sendMessage(message.tabId, message);`

**Comment by rajinder-yadav** [comment] 2017-03-01 16:24
@negue officially we support chrome web browser. Also I've taken a look at vivaldi chrome extension, which I guess is what you're referring too. There is no details about what this plugin is doing, or who develops it. Also it looks like vivaldi plugin is trying to circumvent security by sending page info/data.

Can you please elaborate on what you mean by Vivaldi support? and exactly what you're trying to achieve?

**Comment by negue** [comment] 2017-03-01 21:13
With `Vivaldi Support` I meant, if its possible to use `augury` in the [Vivaldi Web Browser](https://vivaldi.com) which has Chrome under-the-hood

**Comment by rajinder-yadav** [comment] 2017-03-06 09:52
Theoretically it should work out of the box, however we have no idea how the codebase was modified by the Vivaldi team. To avoid supporting all chrome-based browsers, our scope with the small team we have is to only support the official Chrome browser. I hope this answers your question.

If you can reproduce this issue on the chrome browser and provide detailed steps for us to reproduce, we can find take a look at this. Please feel free to open a new issue. I am marking this as we will not support.

**Closed** 2017-03-06 09:52 UTC
Labels: bug, deferred
