### ISSUE TITLE
The scrollbar doesn't working in Router Tree tab

### ISSUE THREAD

**Issue by harley1603** [rangle/augury#1412] opened 2019-11-08 04:12 UTC
Augury: 1.23.0
Date: Fri, 08 Nov 2019 04:04:34 GMT
OS: Win64

Description of issue:
The scrollbar in "Router Tree" tab didn't working well because it didn't shrink automatically based the size of frame, so that i couldn't see the remaining routers
Photo: https://user-images.githubusercontent.com/55377703/68449106-772b0480-0218-11ea-9bd0-89d22392763d.jpg
Angular version (required):  4.4.6

**Comment by TaPO4eg3D** [comment] 2019-11-08 10:36
duplicate of #1405

**Comment by yallen011** [comment] 2019-11-13 22:03
Please check in see if an issue is already opened before creating a new one. if one already exist, it's better to add to the current issue instead of creating a new one.

**Comment by yallen011** [comment] 2019-11-14 18:26
can you share the repo in which you saw this issue?

**Comment by feeloor** [comment] 2019-11-18 13:55
This was fixed as part of #1422, please try building from master, or wait for upcoming release.
I'm closing this, feel free to reopen if your issue wasn't resolved.

Thanks!

**Closed by feeloor** 2019-11-18 13:55 UTC
Labels: duplicate
