### ISSUE TITLE
 TypeError: Cannot redefine property: $$el     at Function.defineProperty (<anonymous>)     at Object.e.consoleReference (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:31:83265)     at chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:31:81185     at j (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:31:78471)

### ISSUE THREAD

**Issue by saurabhdwivedi13** [rangle/augury#1324] opened 2018-07-31 03:32 UTC
Augury: 1.19.1
Date: Tue, 31 Jul 2018 03:29:51 GMT
OS: Win64

Description of issue:
-- When selecting a component it throws error :+1: 
 TypeError: Cannot redefine property: $$el
    at Function.defineProperty (<anonymous>)
    at Object.e.consoleReference (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:31:83265)
    at chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:31:81185
    at j (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:31:78471)

Angular version (required): 5

Steps to reproduce:

1. Open Angular app
2. Go to Developer too;
3. Go to Augury select any component.ts file throws error :+1: 

ypeError: Cannot redefine property: $$el
    at Function.defineProperty (<anonymous>)
    at Object.e.consoleReference (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:31:83265)
    at chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:31:81185
    at j (chrome-extension://elgalmkoelokbchhkhacckoklkejnhcd/build/backend.js:31:78471)

**Comment by keneasson** [comment] 2018-07-31 14:43
Hello, thanks for letting us know.
It looks like the`$$el` property in your window has been set elsewhere as non-configurable. Can you confirm this by running `Object.getOwnPropertyDescriptor(window, '$$el')` from your console?

**Comment by saurabhdwivedi13** [comment] 2018-07-31 14:52
In chrome when I ran this it returned undefined.

**Comment by saurabhdwivedi13** [comment] 2018-07-31 17:14
Please advise with the further course of action, in case I need to change anything.
Thanks !!

**Comment by saurabhdwivedi13** [comment] 2018-07-31 18:48
Now after clicking to a component which are present in my app it is throwing error but when I ran -

Object.getOwnPropertyDescriptor(window, '$$el')

it says {value:"There is no component selected", configurable:false, enumerable:false, writable:false}
kindly suggest.
Thanks !

**Comment by saurabhdwivedi13** [comment] 2018-08-02 05:45
one more observation it is specifically breaking for Angular 5 for Angular 6 it is working fine.

**Comment by RyanOC** [comment] 2018-09-12 18:04
Same error here. Any ideas on a fix?

**Comment by peterblazejewicz** [comment] 2018-09-23 19:00
It happens on clean install of Firefox (MacOS) with only Augury extension being installed.

**Comment by peterblazejewicz** [comment] 2018-09-23 19:56
Can we fix this by:
```diff
diff --git a/src/backend/backend.ts b/src/backend/backend.ts
index a6817f3..8f2bebb 100644
--- a/src/backend/backend.ts
+++ b/src/backend/backend.ts
@@ -444,14 +444,16 @@ export const routerTree = (): Array<any> => {
 };
 
 export const consoleReference = (node: Node) => {
-  Object.defineProperty(window, selectedComponentPropertyKey, {
-    get: () => {
-      if (node) {
-        return ng.probe(node.nativeElement());
+  if (!Object.getOwnPropertyDescriptor(window, selectedComponentPropertyKey)) {
+    Object.defineProperty(window, selectedComponentPropertyKey, {
+      get: () => {
+        if (node) {
+          return ng.probe(node.nativeElement());
+        }
+        return null;
       }
-      return null;
-    }
-  });
+    });
+  }
 };
```

**Comment by saurabhdwivedi13** [comment] 2018-09-26 20:14
Is it going to be fixed in any upcoming release ??

**Comment by saurabhdwivedi13** [comment] 2018-10-19 14:53
Hello ,
Is it going to be fixed in any of future release.
Please advise.

**Comment by maevadevs** [comment] 2019-09-15 01:34
Still having issue on this with latest Angular and Augury canary build.

Augury version (required): Augury Canary Build
Angular version (required): 8.2.6
Date: 2019-09-15T01:23:09.458Z
OS: MacOS 10.14.6

Description of issue:
Clicking on any component in the component tree will throw the following error. Reproduced in both Chrome and Firefox.

![chrome](https://user-images.githubusercontent.com/6579094/64915520-a8aeb480-d72e-11e9-9ecb-3b97b7196f4a.png)

![moz](https://user-images.githubusercontent.com/6579094/64915522-b19f8600-d72e-11e9-8caa-b65396b44f7d.png)

Steps to reproduce:

1. Start Angular Application: Port 4200
2. Open Browser Developer Tools > Augury
3. Click on an Angular component in Augury's Component Tree

**Comment by RPethani** [comment] 2019-09-20 05:31
I have just started to use this tool but unable to explore it further because of this issue. Is there any quick fix ?

**Comment by joaodarocha** [comment] 2019-09-25 11:51
I can also add that it's also happening in Angular 8, i get the same error.


![Uploading Augury Error 1.png…]()

And this is the result of `Object.getOwnPropertyDescriptor(window, '$$el')`.

![Uploading Augury Error 2.png…]()

**Comment by binDongKim** [comment] 2019-11-01 06:54
I'm using Angular 8(accurately 8.2.3) and got the same error.

**Comment by TaPO4eg3D** [comment] 2019-11-06 12:21
I fixed this issue in my PR. You can wait till it's merged or build the extension yourself.

**Closed** 2019-11-18 08:48 UTC
Labels: waiting-for-release
